#!~/usr/bin/python
from flask import Flask, flash, request, render_template, session
from airplanedb import AirplaneDb
import config
import os

app = Flask(__name__)
airdb = AirplaneDb(host=config.host,
                   user=config.dbusr,
                   pw=config.dbpwd,
                   db=config.dbname)

# ---------------------------------------------------------
# HOME
# ---------------------------------------------------------

@app.route('/')
def index():
    if session.get('type') == 'user':
        return 'Logged in as user!'
    elif session.get('type') == 'admin':
        return 'Logged in as admin!'
    else:
        return render_template('index.html')

@app.route('/login', methods=['POST'])
def login():
    if request.form['password'] == config.adminpwd and request.form['username'] == 'admin':
        session['type'] = 'admin'
    elif request.form['password'] == config.userpwd and request.form['username'] == 'user':
        session['type'] = 'user'
    else:
        flash('wrong password!')
    return index()

@app.route('/logout')
def logout():
    session['type'] = 'none'
    return index()

@app.route('/test/<name>')
def test_name(name):
    return 'Welcome, {}!'.format(name)

# ---------------------------------------------------------
# DATABASE ENDPOINTS
# ---------------------------------------------------------
# reset the database
@app.route('/reset')
def reset():
    airdb.reset_db()

    return 'DB HAS BEEN RESET'

# test create new customer
@app.route('/customer')
def add_customer():
    cust_name = request.args.get('name')
    cust_age = request.args.get('age')
    cust_email = request.args.get('email')
    cust_phone = request.args.get('phone')

    airdb.add_customer(cust_name, cust_age, cust_email, cust_phone)

    return 'ADDED NEW CUSTOMER %s' % cust_name
	
@app.route('/ff')
def add_frequent_flier():
    cust_ID = request.args.get('cid')
	miles = 0
	# miles initialized to 0
    airdb.add_frequent_flier(cust_ID, miles)

    return 'WELCOME TO THE FREQUENT FLIER CLUB %s' % cust_ID

@app.route('/ffupdate')
def update_frequent_flier():
	cust_ID = request.args.get('cid')
	miles = request.args.get('miles')
	airdb.update_frequent_flier(cust_ID,miles)
	
	return 'ADDED %s MILES TO ACCOUNT' % miles

if __name__ == '__main__':
    print('Connecting to db...{}'.format(config.dbname))
    app.config['TEMPLATES_AUTO_RELOAD'] = True
    app.secret_key = os.urandom(12)
    app.run()
